//============================================================================
// twiddle_rom.v  -- Parameterized twiddle-factor ROM (cos & sin tables)
//   Holds N/2 entries of cos(2pi k/N) and sin(2pi k/N) in Q1.(TW-1).
//   Contents generated by golden_model.py:
//     twiddle_bw<TW>_cos_hex.txt , twiddle_bw<TW>_sin_hex.txt
//============================================================================
`timescale 1ns/1ps
module twiddle_rom #(
    parameter TW    = 16,
    parameter N     = 1024,
    parameter DEPTH = N/2,
    parameter AW    = $clog2(N/2),
    parameter COS_FILE = "twiddle_bw16_cos_hex.txt",
    parameter SIN_FILE = "twiddle_bw16_sin_hex.txt"
)(
    input               clk,
    input      [AW-1:0] addr,
    output reg signed [TW-1:0] w_cos,
    output reg signed [TW-1:0] w_sin
);
    reg signed [TW-1:0] cos_mem [0:DEPTH-1];
    reg signed [TW-1:0] sin_mem [0:DEPTH-1];

    initial begin
        $readmemh(COS_FILE, cos_mem);
        $readmemh(SIN_FILE, sin_mem);
    end

    always @(posedge clk) begin
        w_cos <= cos_mem[addr];
        w_sin <= sin_mem[addr];
    end
endmodule
